### ISSUE TITLE
pd crash when editing videoPlayerExample macOS 10.14.1 pd 0.49.1 ofelia 2.0.2

### ISSUE THREAD

**Issue by megrimm** [cuinjune/ofxOfelia#5]
Duplicated the videoPlayerExample to edit. When I click on [ofelia] object, make a change to the lua script (simple change such as modifying of.background color and then save (on mac command + s) the background color changes as expected and then Pd crashes.

I assume we can edit lua scripts in real-time?

Anyway attached is the crash report.

Thanks for all the great work btw!

[crash-report-ofelia-2018.11.22.txt](https://github.com/cuinjune/ofxOfelia/files/2609411/crash-report-ofelia-2018.11.22.txt)

**Comment by cuinjune** [comment]
Thank you for reporting this. I could confirm the issue.
I think this happens in all single lua script examples.
I'll try to fix this as soon as possible.

**Comment by cuinjune** [comment]
@megrimm I just fixed the issue and uploaded ofelia v2.0.3 on Deken.
Please check it out.

**Comment by megrimm** [comment]
hmmmm... i only see 2.0.3 for windows and linux in deken.

Thanks!

**Comment by cuinjune** [comment]
I can see it. Can you try again now? Make sure you use 64bit Pd.

**Comment by megrimm** [comment]
yeah still crashes.

pd console states "ofelia v2.0.2 : compiled on Nov 14 2018" after deken 2.0.3 install. also see binary compiled 11/14/18. might wrong version be on deken?

mark

**Comment by cuinjune** [comment]
Showing the "v2.0.2" on the pd console is natural since I didn't re-compile the binary but just changed some Lua scripts. (Maybe I should make it show just "v2.0" to avoid confusion)

Can you open "ofelia/CHANGES.txt" to see there is v2.0.3 at the top?
If you can see it, try opening the "examples/video/videoPlayerExample/main.pd" patch and then try clicking the message box "read -c videoPlayerExample.lua" a few times.

If it crashes, check if you have the following code at the top of "videoPlayerExample.lua" file.
```
if type(window) ~= "userdata" then
  window = pd.OFWindow()
end
```
instead of `local window = pd.OFWindow()`

I also use Pd-0.49-1 on macOS 10.14.1 and the above fix made it no longer crash.
Please try again and let me know how it goes.

**Comment by megrimm** [comment]
ah got it. i was assuming changes were more than just lua scripts. all is working now with ability to modify script and write changes.

yeah i would stick with the v2.0.2, v2.0.3, etc but I guess you would have to recompile binary to get version info in console? unless version info can be read from a text file?

thanks!

**Comment by cuinjune** [comment]
I'm glad it works now.

I think it's a great idea to print the version info by reading the "CHANGES.txt" text file.
I will apply this change in the next update.
Thank you for the idea!
